services:
  - type: web
    name: perfil-work
    env: python
    buildCommand: "apt-get install -y libpango-1.0-0 libpangoft2-1.0-0 && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
